study/urls.py
from django.urls import path
from . import views

app_name = 'study'
urlpatterns = [
    # /study/
    path('', views.index, name='index'),
    # /study/search/
    path('search/', views.search, name='search'),
    # /study/register/
    path('register/', views.register, name='register'),
    # /study/login/
    path('login/', views.user_login, name='user_login'),
    # /study/logout/
    path('logout/', views.user_logout, name='user_logout'),
    # study/<country_id>/
    path('<int:country_id>/', views.detail, name='detail'),
    # study/<country_id>/favorite/
    path('<int:country_id>/favorite/', views.favorite, name='favorite'),
    # study/country/add/
    path('country/add/', views.add_country, name='add_country'),
    # study/country/<country_id>/
    path('country/<int:country_id>/', views.edit_country, name='edit_country'),
    # study/country/<country_id>/delete/
    path('country/<int:country_id>/delete/', views.delete_country, name='delete_country'),
    # study/university/<university_id>/delete/
    path('university/<int:university_id>/delete/', views.delete_univ, name='delete_univ'),
    # study/<country_id>/university/add/
    path('<int:country_id>/university/add/', views.add_university, name='add_university'),
    # study/university/<university_id>
    path('university/<int:university_id>/', views.edit_university, name='edit_university'),
    # study/university/
    path('university/', views.all_university, name='all_university'),
    # study/university/shortlists/
    path('university/shortlists/', views.shortlists, name='shortlists'),
    # study/university/details/<university_id>/
    path('university/details/<int:university_id>/', views.univ_details, name='univ_details'),
    # test
    path('test', views.test1, name='test'),
]

webApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('study/', include('study.urls')),
    path('', include('study.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

study/models.py
from django.db import models
from django.contrib.auth.models import User


class Country(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    language = models.CharField(max_length=250)
    currency = models.CharField(max_length=50)
    country_pic = models.FileField(default='')

    def __str__(self):
        return self.name + " - " + self.language + " - " + self.currency


class University(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    university_name = models.CharField(max_length=1000)
    state = models.CharField(max_length=250)
    rank = models.IntegerField()
    intro_video = models.CharField(max_length=1000, blank=True)
    favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.university_name + " - " + self.state

study/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Country, University


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class CountryForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = ['name', 'language', 'currency', 'country_pic']


class UniversityForm(forms.ModelForm):
    class Meta:
        model = University
        fields = ['university_name', 'state', 'rank', 'intro_video']

study/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from django.views.generic import View
import logging
from .models import Country, University
from .forms import CountryForm, UniversityForm, UserForm


def index(request):
    if not request.user.is_authenticated:
        return render(request, 'study/user_login.html')
    else:
        return render(request, 'study/index.html',
                      {'countries': Country.objects.filter(user=request.user), 'user': request.user})


class indexClass(View):
    model = Country


def delete_country(request, country_id):
    c = get_object_or_404(Country, pk=country_id)
    c.delete()
    return render(request, 'study/index.html',
                  {'countries': Country.objects.filter(user=request.user), 'user': request.user})


def delete_univ(request, university_id):
    u = get_object_or_404(University, pk=university_id)
    u.delete()
    return render(request, 'study/all_university.html', {'university': University.objects.all()})


def search(request):
    q = request.GET.get('query')
    if q:
        country = Country.objects.all()
        univs = University.objects.all()
        country_searched = country.filter(name__icontains=q)
        univ_searched = univs.filter(university_name__icontains=q)
        if not country_searched:
            if not univ_searched:
                context = {
                    'error_message': 'No such Country and University found'
                }
                return render(request, 'study/search.html', context)
            else:
                context = {
                    'univs': univ_searched,
                    'error_message': 'No such Country found'
                }
                return render(request, 'study/search.html', context)
        elif not univ_searched:
            context = {
                'countries': country_searched,
                'error_message': 'No such University found'
            }
            return render(request, 'study/search.html', context)

        return render(request, 'study/search.html', {'univs': univ_searched, 'countries': country_searched})
    else:
        return render(request, 'study/index.html',
                      {'countries': Country.objects.filter(user=request.user), 'user': request.user})


def detail(request, country_id):
    if not request.user.is_authenticated:
        return render(request, 'study/user_login.html')
    else:
        c = get_object_or_404(Country, pk=country_id)
        univs = c.university_set.all().order_by('rank')
        return render(request, 'study/detail.html', {'univs': univs, 'country': c})


def favorite(request, country_id):
    c = get_object_or_404(Country, pk=country_id)
    univs = c.university_set.all().order_by('rank')
    try:
        univ_selected = c.university_set.get(pk=request.POST['university'])
    except (KeyError, University.DoesNotExist):
        return render(request, 'study/detail.html', {
            'univs': c.university_set.all(),
            'country': c,
            'error_message': 'No University selected'
        })
    else:
        univ_selected.favorite = True
        univ_selected.save()
        return render(request, 'study/detail.html', {'univs': univs, 'country': c})


def add_country(request):
    if not request.user.is_authenticated:
        return render(request, 'study/user_login.html')
    else:
        form = CountryForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            country = Country.objects.all()
            for c in country:
                if c.name == form.cleaned_data.get('name'):
                    context = {'form': form, 'error_message': 'Country already present'}
                    return render(request, 'study/add-country.html', context)

            c = form.save(commit=False)
            c.user = request.user
            c.save()
            return render(request, 'study/detail.html', {'univs': c.university_set.all().order_by('rank'), 'country': c})
        return render(request, 'study/add-country.html', {'form': form})


def edit_country(request, country_id):
    country_edited = get_object_or_404(Country, id=country_id)
    form = CountryForm(request.POST or None, request.FILES or None, instance=country_edited)
    if request.method == 'POST':
        if form.is_valid():
            c = form.save()
            u = c.university_set.all().order_by('rank')
            return render(request, 'study/detail.html', {'univs': u, 'country': c})

    return render(request, 'study/add-country.html', {'form': form})


def add_university(request, country_id):
    form = UniversityForm(request.POST or None, request.FILES or None)
    country = get_object_or_404(Country, pk=country_id)
    if form.is_valid():
        all_univs = country.university_set.all()
        for univ in all_univs:
            if univ.university_name == form.cleaned_data.get('university_name'):
                context = {
                    'form': form,
                    'error_message': 'University already present',
                    'country': country
                }
                return render(request, 'study/add-university.html', context)

        u = form.save(commit=False)
        u.country = country
        u.save()
        return render(request, 'study/univ_details.html', {'univs': u})
    return render(request, 'study/add-university.html', {'form': form, 'country': country})


def univ_details(request, university_id):
    if not request.user.is_authenticated:
        return render(request, 'study/user_login.html')
    else:
        univs = get_object_or_404(University, pk=university_id)
        return render(request, 'study/univ_details.html', {'univs': univs})


def all_university(request):
    if not request.user.is_authenticated:
        return render(request, 'study/user_login.html')
    else:
        return render(request, 'study/all_university.html', {'university': University.objects.all()})


def shortlists(request):
    return render(request, 'study/shortlists.html', {'university': University.objects.all()})


def edit_university(request, university_id):
    university_edited = University.objects.get(id=university_id)
    form = UniversityForm(request.POST or None, request.FILES or None, instance=university_edited)
    country = get_object_or_404(Country, pk=university_edited.country.id)
    if request.method == 'POST':
        if form.is_valid():
            u = form.save(commit=False)
            u.country = country
            u.save()
            return render(request, 'study/univ_details.html', {'univs': u})
    return render(request, 'study/add-university.html', {'form': form, 'country': country})


def register(request):
    form = UserForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            u = form.save(commit=False)
            uname = form.cleaned_data.get('username')
            pwd = form.cleaned_data.get('password')
            u.set_password(pwd)
            u.save()
            user = authenticate(username=uname, password=pwd)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return render(request, 'study/index.html',
                                  {'countries': Country.objects.filter(user=user), 'user': user})

    return render(request, 'study/register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        uname = request.POST.get('username')
        pwd = request.POST.get('password')
        user = authenticate(username=uname, password=pwd)

        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'study/index.html',
                              {'countries': Country.objects.filter(user=user), 'user': user})
            else:
                return render(request, 'study/user_login.html', {'error_message': 'User is de-activated'})
        else:
            return render(request, 'study/user_login.html', {'error_message': 'Invalid login'})
    return render(request, 'study/user_login.html')


def user_logout(request):
    logout(request)
    return render(request, 'study/user_login.html')


def test1(request):
    return render(request, 'study/test.html')


############################
# BELOW ARE THE CLASS BASED VIEWS
#############################

class CountryList(generic.ListView):
    template_name = 'study/index.html'
    context_object_name = 'countries'

    def get_queryset(self):
        return Country.objects.all()


class CountryDetail(generic.DetailView):
    model = Country
    template_name = 'study/detail.html'


class CountryCreate(generic.CreateView):
    model = Country
    fields = ['name', 'language', 'currency', 'country_pic']


class CountryEdit(generic.UpdateView):
    model = Country
    fields = ['name', 'language', 'currency', 'country_pic']
    success_url = 'study:detail'


class CountryDelete(generic.DeleteView):
    model = Country
    success_url = 'study:index'

study/templates/study/all_university.html
{% extends 'study/base.html' %}
{% block title %} All Universities WorldWide {% endblock %}
{% block university_active %}active{% endblock %}

{% block body %}
<div class="container-fluid ">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'study:all_university' %}">View All</a></li>
                <li role="presentation"><a href="{% url 'study:shortlists' %}">Shortlists</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>World Ranking</th>
                                <th>University Name</th>
                                <th>State</th>
                                <th>Country</th>
                                <th>Introduction Video</th>
                                <th>Shortlisted</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for u in university %}
                                <tr>
                                    <td>{{ u.rank }}</td>
                                    <td><a href="{% url 'study:univ_details' u.id %}">{{ u.university_name }}</a></td>
                                    <td>{{ u.state }}</td>
                                    <td>
                                        <a href="{% url 'study:detail' u.country.id %}">
                                            <img src="{{ u.country.country_pic.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'study:detail' u.country.id %}">{{ u.country.name }}</a>
                                    </td>
                                    <td>
                                        <a target="_blank" href="{% url 'study:univ_details' u.id %}">
                                            <button type="button" class="btn btn-primary btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>

                                    <td>
                                        {% if u.favorite %}
                                            <img src="https://i.imgur.com/FHabz3Q.png" width="15" height="15">
                                        {% endif %}
                                    </td>
                                    <td>
                                        <form action="{% url 'study:delete_univ' u.id %}" method="post" style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="university_id" value="{{ u.id }}" />
                                            <button type="submit" class="btn btn-danger btn-xs">
                                                <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

study/templates/study/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}World For Study{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <link rel="stylesheet" href="{% static 'study/style.css'  %}" >
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css' />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-static-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'study:index' %}">WorldForStudy</a>
            </div>
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="{% block country_active %}{% endblock %}"><a href="{% url 'study:index' %}"><span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp; Country</a></li>
                    <li class="{% block university_active %}{% endblock %}"><a href="{% url 'study:all_university' %}"><span class="glyphicon glyphicon-education" aria-hidden="true"></span>&nbsp; University</a></li>
                </ul>
                <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'study:search' %}">
                    <div class="form-group">
                        <input type="text" class="form-control" name="query" value="{{ request.GET.query }}" placeholder="Search...">
                    </div>
                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp; Search</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li class="{% block add-country_active %}{% endblock %}"><a href="{% url 'study:add_country' %}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Country</a></li>
                    <li><a href="{% url 'study:user_logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

study/templates/study/detail.html
{% extends 'study/base.html' %}
{% block title %} {{ country.name }}'s University {% endblock %}
{% block country_active %}active{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <!-- Leftside Country details -->
        <div class="col-sm-4 col-md-4">
                <div class="panel panel-default">
                    <div class="panel-body" style="border:solid 1px #007A5C;">
                        <a href="{% url 'study:detail' country.id %}">
                            {% if country.country_pic %}
                                <img src="{{ country.country_pic.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                        <h2>{{ country.name }} <small>{{ country.language }}</small></h2>
                        <h3><b><small>{{ country.currency }}</small></b></h3>
                    </div>
                </div>
        </div>

        <!-- Rightside University details -->
        <div class="col-sm-7 col-md-8">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'study:detail' country.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'study:add_university' country.id %}">Add New University</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>List of all Universities present (rankwise): </h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    {% if univs %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>World Ranking</th>
                            <th>Name</th>
                            <th>Shortlisted</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for u in univs %}
                            <tr>
                                <td>{{ u.rank }}</td>
                                <td><a href="{% url 'study:univ_details' u.id %}">{{ u.university_name }}</a></td>
                                <form action="{% url 'study:favorite' country.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <td>
                                        {% if u.favorite %}
                                            <img src="https://i.imgur.com/FHabz3Q.png" width="15" height="15">
                                        {% else %}
                                            <input type="radio" id="u{{ forLoop.counter }}" name="university" value="{{ u.id }}" />
                                        {% endif %}
                                    </td>
                                    <td>
                                        <input type="submit" class="btn btn-primary btn-xs" value="Shortlist">
                                    </td>
                                </form>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                        <!--
                        <form class="form" action="{% url 'study:favorite' country.id %}" method="POST">
                            {% csrf_token %}
                            {% for u in univs %}
                            <input type="radio" id="u{{ forLoop.counter }}" name="university" value="{{ u.id }}"/>
                              <label for="u{{ forLoop.counter }}" >
                                {{ u }}
                                {% if u.favorite %}
                                    <img src="https://i.imgur.com/FHabz3Q.png" width="15" height="15">
                                {% endif %}
                              </label><br>
                            {% endfor %}
                            <input type="submit" value="Shortlist">
                        </form>
                        -->

                    {% else %}
                        <div class="well">No Universities in your Study Destination.</div>
                    {% endif %}
                </div>
            </div>

        </div>

    </div>
</div>
{% endblock %}

study/templates/study/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-3">{{ field.label_tag }}</label>
        <div class="col-sm-14">{{ field }}</div>
    </div>
{% endfor %}

study/templates/study/index.html
{% extends 'study/base.html' %}
{% block country_active %}active{% endblock %}

{% block body %}
<style>
    .thumbnail {margin-left:15px;margin-right:15px;}
    .thumbnail:hover{border:1px solid #007A5C}
    .thumbnail img{transform:scale(0.98)}
    .thumbnail:hover img{transform:scale(1.01)}
</style>
<div class="container-fluid">
<h1 style="padding-left:13px;">!!!Welcome {{ user.username }} to your Study Destinations!!!</h1>
{% if countries %}
    {% for country in countries %}
    <!--
    <ul style="font-size:24px;font-weight:500;color:#fff;margin-bottom:7px;">
        <li><a href="{% url 'study:detail' country.id %}"> {{ country.name }} </a><br>
            <img src="{{ country.country_pic.url }}" width="220" height="130" style="margin-left:10px">
        </li>
    </ul>
    -->
    <div class="col-sm-2 col-md-4">
        <div class="thumbnail">
            <p class="caption" align="center" style="font-size:24px;vertical-align:top;margin-top:-10px">{{ country.name }}</p>
            <a href="{% url 'study:detail' country.id %}">
                <img src="{{ country.country_pic.url }}" class="img-responsive" style="margin-top:-15px;width:100%;height:250px">
            </a>
            <div class="caption">
                <h4>{{ country.currency }} {{ country.language }}</h4>

                <!-- View Details -->
                <a href="{% url 'study:detail' country.id %}" class="btn btn-success btn-md" role="button">View Details</a>

                <!-- Delete Country -->
                <form action="{% url 'study:delete_country' country.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="country_id" value="{{ country.id }}" />
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>

                <!-- Edit Country -->
                <form action="{% url 'study:edit_country' country.id %}" method="get" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="country_id" value="{{ country.id }}" />
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </button>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}
{% else %}
    <div class="col-sm-12">
        <br>
        <a href="{% url 'study:add_country' %}">
            <button type="button" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>&nbsp; Add Country
            </button>
        </a>
    </div>
{% endif %}
</div>
{% endblock %}

study/templates/study/shortlists.html
{% extends 'study/base.html' %}
{% block title %} Shortlisted Universities WorldWide {% endblock %}
{% block university_active %}active{% endblock %}

{% block body %}
<div class="container-fluid ">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'study:all_university' %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'study:shortlists' %}">Shortlists</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>World Ranking</th>
                                <th>University Name</th>
                                <th>State</th>
                                <th>Country</th>
                                <th>Introduction Video</th>
                                <th>Shortlisted</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for u in university %}
                            {% if u.favorite %}
                                <tr>
                                    <td>{{ u.rank }}</td>
                                    <td><a href="{% url 'study:univ_details' u.id %}">{{ u.university_name }}</a></td>
                                    <td>{{ u.state }}</td>
                                    <td>
                                        <a href="{% url 'study:detail' u.country.id %}">
                                            <img src="{{ u.country.country_pic.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'study:detail' u.country.id %}">{{ u.country.name }}</a>
                                    </td>
                                    <td>
                                        <a target="_blank" href="{% url 'study:univ_details' u.id %}">
                                            <button type="button" class="btn btn-primary btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>

                                    <td>
                                        {% if u.favorite %}
                                            <img src="https://i.imgur.com/FHabz3Q.png" width="15" height="15">
                                        {% endif %}
                                    </td>
                                    <td>
                                        <form action="{% url 'study:delete_univ' u.id %}" method="post" style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="university_id" value="{{ u.id }}" />
                                            <button type="submit" class="btn btn-danger btn-xs">
                                                <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}